# Generated by Django 6.0 on 2026-01-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='expected_keywords',
            field=models.TextField(blank=True, default=''),
        ),
    ]
